FROM tomcat:8-jre8
MAINTAINER nathan@omnimodal.io

RUN apt-get update \
	&& apt-get install -y postgresql-client \
	&& apt-get install -y vim \
	&& apt-get install -y procps

# Install json parser so we can read API key for CreateAPIKey output
RUN wget http://stedolan.github.io/jq/download/linux64/jq
RUN chmod +x ./jq
RUN cp jq /usr/bin/

WORKDIR /
RUN mkdir /usr/local/transitclock
RUN mkdir /usr/local/transitclock/config
RUN mkdir /usr/local/transitclock/logs
RUN mkdir /usr/local/transitclock/cache
RUN mkdir /usr/local/transitclock/data
RUN mkdir /usr/local/transitclock/test
RUN mkdir /usr/local/transitclock/test/config

ADD transitclock/target/*.jar /usr/local/transitclock/
ADD transitclockApi/target/api.war /usr/local/tomcat/webapps
ADD transitclockWebapp/target/web.war /usr/local/tomcat/webapps

ADD config/postgres_hibernate.cfg.xml /usr/local/transitclock/config/hibernate.cfg.xml
ADD config/transitclockConfig.xml /usr/local/transitclock/config/transitclockConfig.xml
ADD transitclock/src/main/resources/logbackGtfs.xml /usr/local/transitclock/config/logbackGtfs.xml

ADD bin/*.sh /

# these will be available to intermediate containers during build
# as long as we supply them from docker-compose
ARG POSTGRES_PORT_5432_TCP_ADDR
ARG POSTGRES_PORT_5432_TCP_PORT
ARG POSTGRES_USER
ARG PGPASSWORD
ARG AGENCYNAME
ARG GTFSRTVEHICLEPOSITIONS

# search and replace in the config files
RUN /set_config.sh

CMD ["./check_db_up.sh", "./start_transitclock.sh"]
