version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT_5432_TCP_ADDR=$POSTGRES_PORT_5432_TCP_ADDR
      - POSTGRES_PORT_5432_TCP_PORT=$POSTGRES_PORT_5432_TCP_PORT
      - PGPASSWORD=$PGPASSWORD
      - AGENCYID=$AGENCYID
      - AGENCYNAME=$AGENCYNAME
      - GTFS_URL=$GTFS_URL
      - GTFSRTVEHICLEPOSITIONS=$GTFSRTVEHICLEPOSITIONS
      - WEBAPP_USER=$WEBAPP_USER
      - WEBAPP_PASSWORD=$WEBAPP_PASSWORD
