version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT_NAME=$ENVIRONMENT_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT_5432_TCP_ADDR=$POSTGRES_PORT_5432_TCP_ADDR
      - POSTGRES_PORT_5432_TCP_PORT=$POSTGRES_PORT_5432_TCP_PORT
      - PGPASSWORD=$PGPASSWORD
      - AGENCYID=$AGENCYID
      - AGENCYNAME=$AGENCYNAME
      - GTFS_URL=$GTFS_URL
      - GTFSRTVEHICLEPOSITIONS=$GTFSRTVEHICLEPOSITIONS
      - WEBAPP_USER=$WEBAPP_USER
      - WEBAPP_PASSWORD=$WEBAPP_PASSWORD
      - FEED_POLLING_RATE_SECS=$FEED_POLLING_RATE_SECS
      - TIMEZONE=$TIMEZONE
      - EMAIL_RECIPIENTS=$EMAIL_RECIPIENTS
      - SMTP_HOST=$SMTP_HOST
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SCHED_BASED_PREDS_POLLING_RATE_MSEC=$SCHED_BASED_PREDS_POLLING_RATE_MSEC
      - CLOUDWATCH_REGION=$CLOUDWATCH_REGION
      - CLOUDWATCH_MONITORING_ENDPOINT=$CLOUDWATCH_MONITORING_ENDPOINT
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
